#! /bin/bash

DOCKER_NAME="stock_embeddings"
CONTAINER_NAME="Sokerin-SE"
SRC="stock_embeddings/Stock_Embedding"
DOCKER_USER_ID=1033 # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=1034
CONTAINER_PORT=8894 # used in launch_container file
HOME='/home/p.sokerin'