
data_path: 'data/all_tickers.csv'
stocks: 'best' # либо передать лист с тикерами

features: 
  Open: 'first'
  High: 'max'
  Low: 'min'
  Close: 'last'
  Volume: 'sum'

pct_change: True

train_start: '2023-10-01'
train_end: '2023-11-01'

test_start: '2023-11-01'
test_end: '2023-11-07'

split: 0.75 # используется, если не заданы train_end и test_start

frequency: 'h' # https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

save: True