A: Healthcare
AAL: Industrials
AAPL: Technology
ABBV: Healthcare
ABNB: Consumer Cyclical
ABT: Healthcare
ACGL: Financial Services
ACN: Technology
ADBE: Technology
ADI: Technology
ADM: Consumer Defensive
ADP: Industrials
ADSK: Technology
AEE: Utilities
AEP: Utilities
AES: Utilities
AFL: Financial Services
AIG: Financial Services
AIZ: Financial Services
AJG: Financial Services
AKAM: Technology
ALB: Basic Materials
ALGN: Healthcare
ALL: Financial Services
ALLE: Industrials
AMAT: Technology
AMCR: Consumer Cyclical
AMD: Technology
AME: Industrials
AMGN: Healthcare
AMP: Financial Services
AMT: Real Estate
AMZN: Consumer Cyclical
ANET: Technology
ANSS: Technology
AON: Financial Services
AOS: Industrials
APA: Energy
APD: Basic Materials
APH: Technology
APTV: Consumer Cyclical
ARE: Real Estate
ATO: Utilities
AVB: Real Estate
AVGO: Technology
AVY: Consumer Cyclical
AWK: Utilities
AXON: Industrials
AXP: Financial Services
AZO: Consumer Cyclical
BA: Industrials
BAC: Financial Services
BALL: Consumer Cyclical
BAX: Healthcare
BBWI: Consumer Cyclical
BBY: Consumer Cyclical
BDX: Healthcare
BEN: Financial Services
BG: Consumer Defensive
BIIB: Healthcare
BIO: Healthcare
BK: Financial Services
BKNG: Consumer Cyclical
BKR: Energy
BLDR: Industrials
BLK: Financial Services
BMY: Healthcare
BR: Technology
BRO: Financial Services
BSX: Healthcare
BWA: Consumer Cyclical
BX: Financial Services
BXP: Real Estate
C: Financial Services
CAG: Consumer Defensive
CAH: Healthcare
CARR: Industrials
CAT: Industrials
CB: Financial Services
CBOE: Financial Services
CBRE: Real Estate
CCI: Real Estate
CCL: Consumer Cyclical
CDNS: Technology
CDW: Technology
CE: Basic Materials
CEG: Utilities
CF: Basic Materials
CFG: Financial Services
CHD: Consumer Defensive
CHRW: Industrials
CHTR: Communication Services
CI: Healthcare
CINF: Financial Services
CL: Consumer Defensive
CLX: Consumer Defensive
CMA: Financial Services
CMCSA: Communication Services
CME: Financial Services
CMG: Consumer Cyclical
CMI: Industrials
CMS: Utilities
CNC: Healthcare
CNP: Utilities
COF: Financial Services
COO: Healthcare
COP: Energy
COR: Healthcare
COST: Consumer Defensive
CPB: Consumer Defensive
CPRT: Industrials
CPT: Real Estate
CRL: Healthcare
CRM: Technology
CSCO: Technology
CSGP: Real Estate
CSX: Industrials
CTAS: Industrials
CTLT: Healthcare
CTRA: Energy
CTSH: Technology
CTVA: Basic Materials
CVS: Healthcare
CVX: Energy
CZR: Consumer Cyclical
D: Utilities
DAL: Industrials
DAY: Technology
DD: Basic Materials
DE: Industrials
DFS: Financial Services
DG: Consumer Defensive
DGX: Healthcare
DHI: Consumer Cyclical
DHR: Healthcare
DIS: Communication Services
DLR: Real Estate
DLTR: Consumer Defensive
DOV: Industrials
DOW: Basic Materials
DPZ: Consumer Cyclical
DRI: Consumer Cyclical
DTE: Utilities
DUK: Utilities
DVA: Healthcare
DVN: Energy
DXCM: Healthcare
EA: Communication Services
EBAY: Consumer Cyclical
ECL: Basic Materials
ED: Utilities
EFX: Industrials
EG: Financial Services
EIX: Utilities
EL: Consumer Defensive
ELV: Healthcare
EMN: Basic Materials
EMR: Industrials
ENPH: Technology
EOG: Energy
EPAM: Technology
EQIX: Real Estate
EQR: Real Estate
EQT: Energy
ES: Utilities
ESS: Real Estate
ETN: Industrials
ETR: Utilities
ETSY: Consumer Cyclical
EVRG: Utilities
EW: Healthcare
EXC: Utilities
EXPD: Industrials
EXPE: Consumer Cyclical
EXR: Real Estate
F: Consumer Cyclical
FANG: Energy
FAST: Industrials
FCX: Basic Materials
FDS: Financial Services
FDX: Industrials
FE: Utilities
FFIV: Technology
FI: Technology
FICO: Technology
FIS: Technology
FITB: Financial Services
FLT: Technology
FMC: Basic Materials
FOX: Communication Services
FOXA: Communication Services
FRT: Real Estate
FSLR: Technology
FTNT: Technology
FTV: Technology
GD: Industrials
GE: Industrials
GEHC: Healthcare
GEN: Technology
GILD: Healthcare
GIS: Consumer Defensive
GL: Financial Services
GLW: Technology
GM: Consumer Cyclical
GNRC: Industrials
GOOG: Communication Services
GOOGL: Communication Services
GPC: Consumer Cyclical
GPN: Industrials
GRMN: Technology
GS: Financial Services
GWW: Industrials
HAL: Energy
HAS: Consumer Cyclical
HBAN: Financial Services
HCA: Healthcare
HD: Consumer Cyclical
HES: Energy
HIG: Financial Services
HII: Industrials
HLT: Consumer Cyclical
HOLX: Healthcare
HON: Industrials
HPE: Technology
HPQ: Technology
HRL: Consumer Defensive
HSIC: Healthcare
HST: Real Estate
HSY: Consumer Defensive
HUBB: Industrials
HUM: Healthcare
HWM: Industrials
IBM: Technology
ICE: Financial Services
IDXX: Healthcare
IEX: Industrials
IFF: Basic Materials
ILMN: Healthcare
INCY: Healthcare
INTC: Technology
INTU: Technology
INVH: Real Estate
IP: Consumer Cyclical
IPG: Communication Services
IQV: Healthcare
IR: Industrials
IRM: Real Estate
ISRG: Healthcare
IT: Technology
ITW: Industrials
IVZ: Financial Services
J: Industrials
JBHT: Industrials
JBL: Technology
JCI: Industrials
JKHY: Technology
JNJ: Healthcare
JNPR: Technology
JPM: Financial Services
K: Consumer Defensive
KDP: Consumer Defensive
KEY: Financial Services
KEYS: Technology
KHC: Consumer Defensive
KIM: Real Estate
KLAC: Technology
KMB: Consumer Defensive
KMI: Energy
KMX: Consumer Cyclical
KO: Consumer Defensive
KR: Consumer Defensive
KVUE: Consumer Defensive
L: Financial Services
LDOS: Technology
LEN: Consumer Cyclical
LH: Healthcare
LHX: Industrials
LIN: Basic Materials
LKQ: Consumer Cyclical
LLY: Healthcare
LMT: Industrials
LNT: Utilities
LOW: Consumer Cyclical
LRCX: Technology
LULU: Consumer Cyclical
LUV: Industrials
LVS: Consumer Cyclical
LW: Consumer Defensive
LYB: Basic Materials
LYV: Communication Services
MA: Financial Services
MAA: Real Estate
MAR: Consumer Cyclical
MAS: Industrials
MCD: Consumer Cyclical
MCHP: Technology
MCK: Healthcare
MCO: Financial Services
MDLZ: Consumer Defensive
MDT: Healthcare
MET: Financial Services
META: Communication Services
MGM: Consumer Cyclical
MHK: Consumer Cyclical
MKC: Consumer Defensive
MKTX: Financial Services
MLM: Basic Materials
MMC: Financial Services
MMM: Industrials
MNST: Consumer Defensive
MO: Consumer Defensive
MOH: Healthcare
MOS: Basic Materials
MPC: Energy
MPWR: Technology
MRK: Healthcare
MRNA: Healthcare
MRO: Energy
MS: Financial Services
MSCI: Financial Services
MSFT: Technology
MSI: Technology
MTB: Financial Services
MTCH: Communication Services
MTD: Healthcare
MU: Technology
NCLH: Consumer Cyclical
NDAQ: Financial Services
NDSN: Industrials
NEE: Utilities
NEM: Basic Materials
NFLX: Communication Services
NI: Utilities
NKE: Consumer Cyclical
NOC: Industrials
NOW: Technology
NRG: Utilities
NSC: Industrials
NTAP: Technology
NTRS: Financial Services
NUE: Basic Materials
NVDA: Technology
NVR: Consumer Cyclical
NWS: Communication Services
NWSA: Communication Services
NXPI: Technology
O: Real Estate
ODFL: Industrials
OKE: Energy
OMC: Communication Services
'ON': Technology
ORCL: Technology
ORLY: Consumer Cyclical
OTIS: Industrials
OXY: Energy
PANW: Technology
PARA: Communication Services
PAYC: Technology
PAYX: Industrials
PCAR: Industrials
PCG: Utilities
PEAK: Real Estate
PEG: Utilities
PEP: Consumer Defensive
PFE: Healthcare
PFG: Financial Services
PG: Consumer Defensive
PGR: Financial Services
PH: Industrials
PHM: Consumer Cyclical
PKG: Consumer Cyclical
PLD: Real Estate
PM: Consumer Defensive
PNC: Financial Services
PNR: Industrials
PNW: Utilities
PODD: Healthcare
POOL: Industrials
PPG: Basic Materials
PPL: Utilities
PRU: Financial Services
PSA: Real Estate
PSX: Energy
PTC: Technology
PWR: Industrials
PXD: Energy
PYPL: Financial Services
QCOM: Technology
QRVO: Technology
RCL: Consumer Cyclical
REG: Real Estate
REGN: Healthcare
RF: Financial Services
RHI: Industrials
RJF: Financial Services
RL: Consumer Cyclical
RMD: Healthcare
ROK: Industrials
ROL: Consumer Cyclical
ROP: Technology
ROST: Consumer Cyclical
RSG: Industrials
RTX: Industrials
RVTY: Healthcare
SBAC: Real Estate
SBUX: Consumer Cyclical
SCHW: Financial Services
SHW: Basic Materials
SJM: Consumer Defensive
SLB: Energy
SNA: Industrials
SNPS: Technology
SO: Utilities
SPG: Real Estate
SPGI: Financial Services
SRE: Utilities
STE: Healthcare
STLD: Basic Materials
STT: Financial Services
STX: Technology
STZ: Consumer Defensive
SWK: Industrials
SWKS: Technology
SYF: Financial Services
SYK: Healthcare
SYY: Consumer Defensive
T: Communication Services
TAP: Consumer Defensive
TDG: Industrials
TDY: Technology
TECH: Healthcare
TEL: Technology
TER: Technology
TFC: Financial Services
TFX: Healthcare
TGT: Consumer Defensive
TJX: Consumer Cyclical
TMO: Healthcare
TMUS: Communication Services
TPR: Consumer Cyclical
TRGP: Energy
TRMB: Technology
TROW: Financial Services
TRV: Financial Services
TSCO: Consumer Cyclical
TSLA: Consumer Cyclical
TSN: Consumer Defensive
TT: Industrials
TTWO: Communication Services
TXN: Technology
TXT: Industrials
TYL: Technology
UAL: Industrials
UBER: Technology
UDR: Real Estate
UHS: Healthcare
ULTA: Consumer Cyclical
UNH: Healthcare
UNP: Industrials
UPS: Industrials
URI: Industrials
USB: Financial Services
V: Financial Services
VFC: Consumer Cyclical
VICI: Real Estate
VLO: Energy
VLTO: Industrials
VMC: Basic Materials
VRSK: Industrials
VRSN: Technology
VRTX: Healthcare
VTR: Real Estate
VTRS: Healthcare
VZ: Communication Services
WAB: Industrials
WAT: Healthcare
WBA: Healthcare
WBD: Communication Services
WDC: Technology
WEC: Utilities
WELL: Real Estate
WFC: Financial Services
WHR: Consumer Cyclical
WM: Industrials
WMB: Energy
WMT: Consumer Defensive
WRB: Financial Services
WRK: Consumer Cyclical
WST: Healthcare
WTW: Financial Services
WY: Real Estate
WYNN: Consumer Cyclical
XEL: Utilities
XOM: Energy
XRAY: Healthcare
XYL: Industrials
YUM: Consumer Cyclical
ZBH: Healthcare
ZBRA: Technology
ZION: Financial Services
ZTS: Healthcare
